### ISSUE TITLE
broken captcha audio files ?

### ISSUE THREAD

**Issue by xtekky** [useragents/Funcaptcha-Audio-Solver#4]
So I have been working on some twitch gens including a funcaptcha solver, but after the request to get a token and then audio challenge, the audio file is "broken"/ unplayable. Is this normal ?, did it get patched? and if not, am I doing anything wrong?

**Comment by Hazza3100** [comment]
> 

Hey there @xtekky twitch removed audio from there site, so you can no longer bypass the captcha with audio. You could use a img solver or smt.

**Comment by xtekky** [comment]
Ohh, that's why, and where can I find docu on the api's to get the captcha to solve, I'll try myself but not been reversing twitch for long.

**Comment by useragents** [comment]
Please ensure that you are saving the audio file correctly to prevent the file from being "broken" or "unplayable"

As @Hazza3100 said, you cannot get audio challenges anymore. The reason why you are getting an unplayable audio file is likely because there is no audio content to play, open the `audio.wav` file in Notepad and view the content. It will likely say denied access or other considering they do not support audio challenges on register anymore.

Twitch does allow you to use audio challenges on login attempts currently, I am not responsible for your actions.

I do not understand what you mean by documentation on "api's to get the captcha to solve", the API that returns the images or?

**Comment by xtekky** [comment]
yes, you can get an audio challenge on arkoselabs and also image challenges, but its different params or api I assume

**Comment by useragents** [comment]
@xtekky You can find them yourself through network traffic, use applications like Fiddler, Charles, Wireshark, etc to find the requests you're looking for.
